beclood_top_recettes_homepage:
    path:     /index
    defaults: { _controller: BeCloodTopRecettesBundle:Default:index }


addition:
    path: /addition/{first}/{second}
    defaults: { _controller: BeCloodTopRecettesBundle:OperationsMathematiques:addition}
    requirements:
        first: '\d+'
        second: '\d+'

multiplication:
    path: /multiplication/{first}/{second}
    defaults: { _controller: BeCloodTopRecettesBundle:OperationsMathematiques:multiplication}
    requirements:
        first: '\d+'
        second: '\d+'

beclood_top_recettes_contact:
  path: /contact
  defaults: { _controller: BeCloodTopRecettesBundle:Default:contact }

ezplatform_api:
  path: /api/{id}
  defaults: { _controller: BeCloodTopRecettesBundle:EzPlatform:Api, id: 52 }

alert:
  path: /alert
  defaults: { _controller: BeCloodTopRecettesBundle:Default:alert }