services:
    beclood_top_recettes.formulairecontact_manager:
        class: BeClood\TopRecettesBundle\Utils\FormulaireContactManager
        arguments: ["@doctrine.orm.entity_manager"]
    beclood_top_recettes.search_helper:
        class: BeClood\TopRecettesBundle\Utils\SearchHelper
    becloop_top_recettes.recettes_helper:
        class: BeClood\TopRecettesBundle\Utils\RecettesHelper
        arguments: ["@ezpublish.api.repository", "@beclood_top_recettes.search_helper", "@ezpublish.config.resolver"]
    becloop_top_recettes.mailer_helper:
        class: BeClood\TopRecettesBundle\Utils\MailerHelper
        arguments: ["@twig", "@mailer"]