<?php

namespace BeClood\TopRecettesBundle\Repository;

/**
 * FormulaireContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireContactRepository extends \Doctrine\ORM\EntityRepository
{
}
