imports:
    - { resource: override.yml }

ezpublish:
    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: "%search_engine%"
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site, admin, site_fr]
        groups:
            site_group: [site, admin]
            front_group: [site_fr, site]
        default_siteaccess: site
        match:
            Map\Host:
              fr.ezplatform_formation.loc: site_fr
              ezplatform_formation.loc: site

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_fr:
            languages: [fre-FR, eng-GB]
        site:
            languages: [eng-GB]
        default:
            # Pool to use for cache, needs to be different per repository (database).
            cache_pool_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
#            languages: [eng-GB]
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [770] }

ez_publish_legacy:
    system:
        admin:
           legacy_mode: true
